version: "3"

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - sammelband-network
    volumes:
      - ./server:/usr/src/app
    environment:
      - CLIENT=http://localhost:3000
    command: /usr/src/app/node_modules/.bin/nodemon -L index.js


networks:
  sammelband-network:
    driver: bridge